name: released

on:
  release:
    types: [ released ]

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
    - name: Dispatch event
      uses: actions/github-script@v6
      with: 
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          console.log(context, context.workflow);
